import Head from "next/head";
import { AiFillLinkedin, AiFillYoutube, AiFillGithub, AiFillMessage, AiFillMail } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Skills from "./components/skills";
import Image from "next/image";

import ems from "../public/Employee.png";
import drivingTest from "../public/drivingTest.png";

import Blob from "./components/blob";
import Internships from "./components/internships";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title >Swapnil Nanavati</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className=" flex justify-between pt-10 dark:text-white">
            <h1 className="font-medium text-xl text-teal-600">Swapnil Nanavati</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="ml-8 text-white rounded-md border-none bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                  href="https://drive.google.com/file/d/1Tb8yjSkZ6I8ihS1dwqeeYL8IL0KaNlmO/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 pb-10 pt-0 text-center">
          <div className="relative mx-auto mt-20 mb-10 h-80 w-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
          <Image src={deved} layout="fill" objectFit="cover" />
            </div>
            <h2 className="py-2 text-5xl font-medium text-teal-600 md:text-6xl dark:text-teal-400">
              Swapnil Nanavati
            </h2>
            <h3 className="py-4 text-2xl md:text-3xl dark:text-white">
              Full-Stack Developer
            </h3>
         
             
           
            <p className="text-2xl mx-auto max-w-xl py-5 leading-8 text-gray-700 md:text-2xl dark:text-gray-200">
              Developer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="flex justify-center gap-6 py-3 text-5xl text-teal-600 dark:text-gray-400">
              <AiFillGithub
                className="cursor-pointer  hover:text-teal-800"
                onClick={() => {
                  window.location = "https://github.com/swapnil1411";
                }}
              />
              <AiFillLinkedin
                className="cursor-pointer  hover:text-teal-800"
                onClick={() => {
                  window.location =
                    "https://www.linkedin.com/in/swapnil-nanavati-181989199/";
                }}
              />

              <AiFillMail
                className="cursor-pointer  hover:text-teal-800"
                onClick={() => {
                  window.open('mailto:swapnilnanavati12@gmail.com');
                }}
              />
            </div>
            
          </div>
        </section>
   <Skills/>
       <Internships />
      </main>
    </div>
  );
}
