import Head from "next/head";
import { AiFillLinkedin, AiFillYoutube, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Skills from "./components/skills";
import Image from "next/image";

import ems from "../public/Employee.png";
import drivingTest from "../public/drivingTest.png";

import Blob from "./components/blob";
import Internships from "./components/internships";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Swapnil's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="mb-12 flex justify-between py-10 dark:text-white">
            <h1 className="font-burtons text-xl">Swapnil's Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="ml-8 text-white rounded-md border-none bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                  href="https://drive.google.com/file/d/1Tb8yjSkZ6I8ihS1dwqeeYL8IL0KaNlmO/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="p-10 py-10 text-center">
          <div className="relative mx-auto mt-20 h-80 w-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
          <div style={{ position: 'relative', width: '100%', height: '100%' }}>
          <Blob dark={darkMode} style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }} />
          <Image src={deved} layout="fill" objectFit="cover" />
        </div>
            </div>
            <h2 className="py-2 text-5xl font-medium text-teal-600 md:text-6xl dark:text-teal-400">
              Swapnil Nanavati
            </h2>
            <h3 className="py-2 text-2xl md:text-3xl dark:text-white">
              Developer
            </h3>
         
             
           
            <p className="text-md mx-auto max-w-xl py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-200">
              Developer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-400">
              <AiFillGithub
                className="cursor-pointer"
                onClick={() => {
                  window.location = "https://github.com/swapnil1411";
                }}
              />
              <AiFillLinkedin
                className="cursor-pointer"
                onClick={() => {
                  window.location =
                    "https://www.linkedin.com/in/swapnil-nanavati-181989199/";
                }}
              />
            </div>
            
          </div>
        </section>
   <Skills/>
       <Internships />
      </main>
    </div>
  );
}
